### ISSUE TITLE
building failure on mac

### ISSUE THREAD

**Issue by Thorneblade** [haxpor/aseprite-macos-buildsh#19]
I'm running a macOS Mojave and whenever I run "python2 tools/git-sync-deps" I get this first see this: 

fatal: remote error: Git repository not found.

 and then it follows with this: Exception in thread Thread-11:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 132, in git_checkout_to_directory
    [git, 'clone', '--quiet', repo, directory])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', 'https://skia.googlesource.com/third_party/libjpeg-turbo.git', 'third_party/externals/libjpeg-turbo']' returned non-zero exit status 128.

And finally, I get this:

Traceback (most recent call last):
  File "bin/fetch-gn", line 32, in <module>
    f.write(urllib2.urlopen('https://chromium-gn.storage-download.googleapis.com/' + sha1).read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Traceback (most recent call last):
  File "tools/git-sync-deps", line 253, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 248, in main
    os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'bin/fetch-gn']' returned non-zero exit status 1

I have no idea what any of this means or how to fix it.
Can someone help me?

**Comment by ghost** [comment]
I encountered the same issue, how could you solve this problem? Could tell me?/small
