### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Muscarv2** [haxpor/aseprite-macos-buildsh#7]
I've made sure I have all pre-requisites installed. I get many errors and it doesn't create the aseprite.app. Here's from the last line where everything is fine to the end:

```
third_party/externals/swiftshader    @ d6126aea667e37d2d7b57b0a381b9f26912a21b7
Traceback (most recent call last):
  File "bin/fetch-gn", line 32, in <module>
    f.write(urllib2.urlopen('https://chromium-gn.storage-download.googleapis.com/' + sha1).read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
Traceback (most recent call last):
  File "tools/git-sync-deps", line 253, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 248, in main
    os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'bin/fetch-gn']' returned non-zero exit status 1
gn.py: Could not find gn executable at: /Users/M/Downloads/aseprite-macos-buildsh-for-aseprite-1.2.10/deps/skia/buildtools/mac/gn
ninja: Entering directory 'out/Release'
ninja: fatal: chdir to 'out/Release' - No such file or directory
Note: checking out 'v1.2.15-74-g5ac07c082'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5ac07c082 Fix pressing buttons with Alt+mnemonic or Cmd+mnemonic (regression introduced in 536a4c5d3aedccb4f24c5a5e28324ddad7638e18)
aseprite.sh: line 149: cmake: command not found
```

**Comment by haxpor** [comment]
I have moved on from macOS machine. Anyway, for your problem, it's about `urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>`. Pretty much painful error I also found.

I cannot remember exactly which solution I used long ago to resolve this. It's per machine basis. I believe it's about the machine has the certificate prior to connecting to remote https server, or that sort of stuff.

Please try [this](https://github.com/yoavaviram/python-amazon-simple-product-api/issues/129#issuecomment-372084644) (but try searching for pythong 2.x instead), or [this](https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/).

**Comment by MiLeG** [comment]
I had the same issue. Seems like installing the python certificates did the trick for me.

**Comment by haxpor** [comment]
If the problem still persist, feel free to reopen.
